version: '3'

services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    volumes:
      - ./deployment/mariadb/db:/var/lib/mysql
      - ./deployment/mariadb/conf:/etc/mysql/conf.d

#  mariadb_test:
#    image: mariadb:10.4
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: db_test
#      MYSQL_USER: user1
#      MYSQL_PASSWORD: password1
#    volume:
#      - ./deployment/mariadb_test/db:/var/lib/mysql
#      - ./deployment/mariadb_test/conf:/etc/mysql/conf.d

  redis:
    image: redis:alpine

  frontend:
    build: ./deployment/frontend
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=dev
    volumes:
      - ./frontend:/home/node/app

  backend:
    build: ./deployment/backend
    ports:
      - "5000:80"
    volumes:
      - ./backend:/var/www/html
      - ./deployment/backend/sites-enabled:/etc/apache2/sites-enabled
    depends_on:
      - mariadb

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - mariadb

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
