api_platform:
    title: 'Portal API'
    description: 'Users API'
    version: '1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
