gesdinet_jwt_refresh_token:
  firewall: refresh_token
  single_use: true
  token_parameter_name: refreshToken
  ttl: 1800
  user_identity_field: username
  user_provider: security.user.provider.concrete.db_provider
