framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER)% <%env(MAILER_FROM)%>'
        headers:
            from: '%env(MAILER_SENDER)% <%env(MAILER_FROM)%>'
            bcc: '%env(MAILER_BCC)%'
