# todo template le-ssl
- name: Create vhost back
  become: true
  become_user: root
  template:
    src: templates/vhost_back.conf.j2
    dest: "/etc/apache2/sites-available/{{ back_server_name }}.conf"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '0644'

# todo template le-ssl
- name: Create vhost front
  become: true
  become_user: root
  template:
    src: templates/vhost_front.conf.j2
    dest: "/etc/apache2/sites-available/{{ front_server_name }}.conf"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '0644'

- name: Enable site
  become: true
  become_user: root
  command: a2ensite {{ item }}
  loop:
    - "{{ back_server_name }}"
    - "{{ front_server_name }}"

# todo no create le-ssl
- name: Certbot
  become: true
  become_user: root
  shell:
    creates: "/etc/letsencrypt/live/{{ item }}"
    cmd: "certbot --apache --agree-tos --non-interactive -d {{ item }} -m {{ admin_email }}"
  notify: restart apache2
  loop:
    - "{{ back_server_name }}"
    - "{{ front_server_name }}"
