- name: Deploy files
  copy:
    src: '{{ playbook_dir }}/../../frontend/{{ item }}'
    dest: "{{ app_directory }}/frontend/"
    owner: "{{ maintainer_user }}"
    group: "{{ maintainer_user }}"
    mode: '755'
  loop:
    - '.eslintrc.js'
    - '.stylelintrc.js'
    - 'babel.config.js'
    - 'package.json'
    - 'tsconfig.json'
    - 'vue.config.js'
    - 'yarn.lock'

- name: Deploy directories
  synchronize:
    delete: true
    src: '{{ playbook_dir }}/../../frontend/{{ item }}'
    dest: "{{ app_directory }}/frontend/"
    recursive: true
    rsync_opts:
      - "--chown={{ maintainer_user }}:{{ maintainer_user }}"
      - '--chmod=0755'
  loop:
    - 'public'
    - 'src'
