name: Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/docker

    steps:
      - uses: actions/checkout@v2

      - name: Pull images
        run: docker-compose -f docker-compose-ci.yml pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Copy env file
        run: cp .env.example .env

      - name: Create var folder
        working-directory: ./backend
        run: mkdir var var/cache var/log

      - name: Build docker-compose services
        run: docker-compose -f docker-compose-ci.yml up -d

#      - name: docker ps
#        run: docker-compose ps
#
#      - name: docker log
#        run: docker-compose logs backend

      - name: Validate composer.json and composer.lock
        run: docker-compose -f docker-compose-ci.yml exec -T backend composer validate --strict

      - name: Install dependencies
        run: docker-compose -f docker-compose-ci.yml exec -T backend composer install --prefer-dist --no-interaction --no-suggest

      - name: Install PHPUnit
        run: docker-compose -f docker-compose-ci.yml exec -T backend ./vendor/bin/simple-phpunit install

      - name: PHP CS Fixer
        run: docker-compose -f docker-compose-ci.yml exec -T backend composer run cs

      - name: PHPStan
        run: docker-compose -f docker-compose-ci.yml exec -T backend bash -c "php -d memory_limit=2G vendor/bin/phpstan"

      - name: Migrations
        run: docker-compose -f docker-compose-ci.yml exec -T backend bin/console --no-interaction doctrine:migration:migrate -e test

      - name: PHPUnit
        run: docker-compose -f docker-compose-ci.yml exec -T backend composer run tu-ci

# marche po...
#      # coverallsapp/github-action@master only support lcov.info file for now
#      - name: Upload coverage results to Coveralls
#        run: docker-compose -f docker-compose-ci.yml exec -T bash -c "COVERALLS_REPO_TOKEN=${{ github.token }} COVERALLS_FLAG_NAME=back-unit vendor/bin/php-coveralls --coverage_clover=ci/coverage/unit/clover.xml --json_path=ci/coverage/unit/coveralls-upload.json -vvv"

# todo separate unit and functional coverage
