name: Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/docker

    steps:
      - uses: actions/checkout@v2

      - name: Pull images
        run: docker-compose -f ./docker-compose-ci.yml pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Copy env file
        run: cp .env.example .env

      - name: Build docker-compose services
        run: docker-compose --env-file=.env.example -f ./docker-compose-ci.yml up -d

      - name: Validate composer.json and composer.lock
        run: docker-compose run backend composer validate --strict

      - name: Install dependencies
        run: docker-compose run backend composer install --prefer-dist --no-interaction --no-suggest

      - name: Install PHPUnit
        run: docker-compose run backend ./vendor/bin/simple-phpunit install

      - name: PHP CS Fixer
        run: docker-compose run backend composer run cs

      - name: PHPStan
        run: docker-compose exec -T backend composer run ps

      - name: Migrations
        run: docker-compose run backend bin/console --no-interaction doctrine:migration:migrate -e test

      - name: PHPUnit
        run: docker-compose run backend composer run tu-ci

      # coverallsapp/github-action@master only support lcov.info file for now
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
          COVERALLS_FLAG_NAME: back-unit
        run: |
          docker-compose run composer global require php-coveralls/php-coveralls
          docker-compose run ~/.composer/vendor/bin/php-coveralls -v

# todo separate unit and functional coverage
