name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Copy config file
        run: cp ./config/variables.example.json ./config/variables.json

      - name: Install dependencies
        run: yarn install

      - name: Lint js
        run: npm run lint

      - name: Lint style
        run: npm run lint:style

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:ucov

#      - name: debug
#        run: cat ${{ github.workspace }}/frontend/ci/coverage/unit/lcov.info

# why coveralls empty ?
      - name: Unit tests coverage
        uses: coverallsapp/github-action@master
        with:
          base-path: frontend
          flag-name: front-unit
          github-token: ${{ github.token }}
          path-to-lcov: ${{ github.workspace }}/frontend/ci/coverage/unit/lcov.info

      - name: End to end tests
        run: npm run test:e2e

# todo coverage e2e
