name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/frontend

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Copy config file
        run: cp ./config/variables.example.json ./config/variables.json

      - name: Install dependencies
        run: yarn install

      - name: Lint js
        run: npm run lint

      - name: Lint style
        run: npm run lint:style

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:ucov

      - name: Codecov unit
        run: bash <(curl -s https://codecov.io/bash) -F frontend,front-unit -f "./ci/coverage/unit/clover.xml"

      - name: End to end tests
        run: npm run test:e2ecov

      - name: Codecov e2e
        run: bash <(curl -s https://codecov.io/bash) -F frontend,front-e2e -f "./ci/coverage/e2e/clover.xml"
