name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/frontend

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Copy config file
        run: cp ./config/variables.example.json ./config/variables.json

      - name: Install dependencies
        run: yarn install

      - name: Lint js
        run: npm run lint

      - name: Lint style
        run: npm run lint:style

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:ucov

      - uses: nelonoel/branch-name@v1.0.1

      - name: Unit tests coverage
        run: ./node_modules/coveralls/bin/coveralls.js < ./ci/coverage/unit/lcov.info
        env:
          COVERALLS_SERVICE_NAME: 'github'
          COVERALLS_REPO_TOKEN: ${{ github.token }}
          COVERALLS_GIT_COMMIT: ${{ github.sha }}
          COVERALLS_GIT_BRANCH: ${{ env.BRANCH_NAME }}
          COVERALLS_SERVICE_JOB_ID: ${{ github.run.id }}
          COVERALLS_FLAG_NAME: 'front-unit'

      - name: End to end tests
        run: npm run test:e2e

# todo coverage e2e
